version: '3.7'
services:
  web:
    build: ./social_network_test_2
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./social_network_test/:/usr/src/social_network_test_2/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev