# Generated by Django 4.0.4 on 2022-05-30 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-data_add',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='data_add',
        ),
    ]
